### ISSUE TITLE
Merge pre_release into develop

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-website#255]
Merge `pre_release` into `develop` once the following issues have been merged into `pre_release`:
- [x] Task/#237 - Change logo in progress
- [x] Task/#238 - Create contact us link on menu and footer in progress
- [x] Task/#236 - Remove get started page from carbon ldp website in progress
- [x] Task/#234 - Update css website styles according to new designs in progress
- [x] Task/#233 - Draft new linked data page in progress
- [x] Task/#232 - Draft new carbon ldp page in progress
- [x] Task/#231 - Draft new home page in progress
- [x] Task/#229 - Draft new about us page in progress
- [x] Task/#228 - Create new footer in progress
- [x] Task/#227 - Move community and support menu underneath documentation menu
- [x] Task/#241 - Create new partial for contact form in progress
- [x] Task/#240 - Create new partial for download white paper form in progress
